const catalyst = require("zcatalyst-sdk-node");

module.exports = async (context, basicIO) => {
  try {
    const app = catalyst.initialize(context);

    const table = app.datastore().table("34995000000121039");

    const employees = [
      {
        emp_id: "EMP001",
        name: "Amit Kumar",
        designation: "Software Engineer",
        reporting_manager: "Rajesh Sharma",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Rajesh Sharma",
        status: "Active",
        wissen_experience: 1.5,
        total_experience: 2.0,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Exceeds Expectations",
        interview_count: 4,
        rr_percent: 82.5,
        gross_margin: 28.4,
        rb_to_be_paid: 18000,
        month_rb: "Mar",
        pb_to_be_paid: 25000,
        month_pb: "Mar",
        current_annual_base_pay: 600000,
        target_pb_allocated_for_may: 30000,
        allocated_pb_amount: 28000,
        pb_installment: "2",
        new_pb_to_be_offered: 35000,
        new_pb_installment: "2",
        new_rb: 20000,
        hike_amount: 48000,
        hike_pct: 8.0,
        target_pb_next_year: 40000,
        eligible_for_promotion: "No",
        new_title: "Software Engineer",
        at_risk: "No",
      },
      {
        emp_id: "EMP002",
        name: "Priya Das",
        designation: "Software Engineer",
        reporting_manager: "Rajesh Sharma",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Rajesh Sharma",
        status: "Active",
        wissen_experience: 2.2,
        total_experience: 3.1,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Outstanding",
        interview_count: 6,
        rr_percent: 91.2,
        gross_margin: 32.6,
        rb_to_be_paid: 22000,
        month_rb: "Mar",
        pb_to_be_paid: 30000,
        month_pb: "Mar",
        current_annual_base_pay: 720000,
        target_pb_allocated_for_may: 36000,
        allocated_pb_amount: 35000,
        pb_installment: "2",
        new_pb_to_be_offered: 45000,
        new_pb_installment: "2",
        new_rb: 25000,
        hike_amount: 64800,
        hike_pct: 9.0,
        target_pb_next_year: 50000,
        eligible_for_promotion: "Yes",
        new_title: "Senior Software Engineer",
        at_risk: "No",
      },
      {
        emp_id: "EMP003",
        name: "Rahul Patnaik",
        designation: "Senior Software Engineer",
        reporting_manager: "Rajesh Sharma",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Rajesh Sharma",
        status: "Active",
        wissen_experience: 3.5,
        total_experience: 5.0,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Outstanding",
        interview_count: 8,
        rr_percent: 94.5,
        gross_margin: 36.8,
        rb_to_be_paid: 26000,
        month_rb: "Mar",
        pb_to_be_paid: 35000,
        month_pb: "Mar",
        current_annual_base_pay: 900000,
        target_pb_allocated_for_may: 45000,
        allocated_pb_amount: 44000,
        pb_installment: "2",
        new_pb_to_be_offered: 55000,
        new_pb_installment: "2",
        new_rb: 30000,
        hike_amount: 90000,
        hike_pct: 10.0,
        target_pb_next_year: 60000,
        eligible_for_promotion: "Yes",
        new_title: "Lead Software Engineer",
        at_risk: "No",
      },
      {
        emp_id: "EMP004",
        name: "Sneha Mohanty",
        designation: "QA Engineer",
        reporting_manager: "Sanjay Rao",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Quality Assurance",
        manager: "Sanjay Rao",
        status: "Active",
        wissen_experience: 1.8,
        total_experience: 2.5,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Meets Expectations",
        interview_count: 3,
        rr_percent: 78.4,
        gross_margin: 25.5,
        rb_to_be_paid: 15000,
        month_rb: "Mar",
        pb_to_be_paid: 22000,
        month_pb: "Mar",
        current_annual_base_pay: 540000,
        target_pb_allocated_for_may: 27000,
        allocated_pb_amount: 25000,
        pb_installment: "1",
        new_pb_to_be_offered: 30000,
        new_pb_installment: "2",
        new_rb: 18000,
        hike_amount: 37800,
        hike_pct: 7.0,
        target_pb_next_year: 35000,
        eligible_for_promotion: "No",
        new_title: "QA Engineer",
        at_risk: "No",
      },
      {
        emp_id: "EMP005",
        name: "Vikash Behera",
        designation: "Software Developer",
        reporting_manager: "Anil Kumar",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Anil Kumar",
        status: "Active",
        wissen_experience: 2.7,
        total_experience: 3.5,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Exceeds Expectations",
        interview_count: 5,
        rr_percent: 86.7,
        gross_margin: 30.2,
        rb_to_be_paid: 20000,
        month_rb: "Mar",
        pb_to_be_paid: 28000,
        month_pb: "Mar",
        current_annual_base_pay: 660000,
        target_pb_allocated_for_may: 33000,
        allocated_pb_amount: 32000,
        pb_installment: "2",
        new_pb_to_be_offered: 40000,
        new_pb_installment: "2",
        new_rb: 22000,
        hike_amount: 59400,
        hike_pct: 9.0,
        target_pb_next_year: 45000,
        eligible_for_promotion: "No",
        new_title: "Software Developer",
        at_risk: "No",
      },
      {
        emp_id: "EMP006",
        name: "Ananya Mishra",
        designation: "Business Analyst",
        reporting_manager: "Meera Nair",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Non Technical",
        department: "Business Analysis",
        manager: "Meera Nair",
        status: "Active",
        wissen_experience: 2.0,
        total_experience: 3.0,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Exceeds Expectations",
        interview_count: 5,
        rr_percent: 84.3,
        gross_margin: 29.8,
        rb_to_be_paid: 19000,
        month_rb: "Mar",
        pb_to_be_paid: 26000,
        month_pb: "Mar",
        current_annual_base_pay: 630000,
        target_pb_allocated_for_may: 31500,
        allocated_pb_amount: 30000,
        pb_installment: "2",
        new_pb_to_be_offered: 38000,
        new_pb_installment: "2",
        new_rb: 21000,
        hike_amount: 50400,
        hike_pct: 8.0,
        target_pb_next_year: 42000,
        eligible_for_promotion: "No",
        new_title: "Business Analyst",
        at_risk: "No",
      },
      {
        emp_id: "EMP007",
        name: "Sourav Das",
        designation: "Software Engineer",
        reporting_manager: "Anil Kumar",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Anil Kumar",
        status: "Active",
        wissen_experience: 1.2,
        total_experience: 1.8,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Meets Expectations",
        interview_count: 2,
        rr_percent: 75.6,
        gross_margin: 24.2,
        rb_to_be_paid: 14000,
        month_rb: "Feb",
        pb_to_be_paid: 20000,
        month_pb: "Feb",
        current_annual_base_pay: 500000,
        target_pb_allocated_for_may: 25000,
        allocated_pb_amount: 24000,
        pb_installment: "1",
        new_pb_to_be_offered: 28000,
        new_pb_installment: "2",
        new_rb: 16000,
        hike_amount: 30000,
        hike_pct: 6.0,
        target_pb_next_year: 32000,
        eligible_for_promotion: "No",
        new_title: "Software Engineer",
        at_risk: "No",
      },
      {
        emp_id: "EMP008",
        name: "Ritika Singh",
        designation: "HR Executive",
        reporting_manager: "Meera Nair",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Non Technical",
        department: "Human Resources",
        manager: "Meera Nair",
        status: "Active",
        wissen_experience: 2.4,
        total_experience: 3.2,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Exceeds Expectations",
        interview_count: 7,
        rr_percent: 88.1,
        gross_margin: 27.5,
        rb_to_be_paid: 18000,
        month_rb: "Mar",
        pb_to_be_paid: 24000,
        month_pb: "Mar",
        current_annual_base_pay: 580000,
        target_pb_allocated_for_may: 29000,
        allocated_pb_amount: 28000,
        pb_installment: "2",
        new_pb_to_be_offered: 35000,
        new_pb_installment: "2",
        new_rb: 20000,
        hike_amount: 46400,
        hike_pct: 8.0,
        target_pb_next_year: 38000,
        eligible_for_promotion: "No",
        new_title: "HR Executive",
        at_risk: "No",
      },
      {
        emp_id: "EMP009",
        name: "Abhishek Nayak",
        designation: "Software Engineer",
        reporting_manager: "Rajesh Sharma",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Rajesh Sharma",
        status: "Active",
        wissen_experience: 3.0,
        total_experience: 4.2,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Outstanding",
        interview_count: 9,
        rr_percent: 96.2,
        gross_margin: 38.5,
        rb_to_be_paid: 28000,
        month_rb: "Mar",
        pb_to_be_paid: 38000,
        month_pb: "Mar",
        current_annual_base_pay: 840000,
        target_pb_allocated_for_may: 42000,
        allocated_pb_amount: 41000,
        pb_installment: "2",
        new_pb_to_be_offered: 52000,
        new_pb_installment: "2",
        new_rb: 28000,
        hike_amount: 84000,
        hike_pct: 10.0,
        target_pb_next_year: 58000,
        eligible_for_promotion: "Yes",
        new_title: "Senior Software Engineer",
        at_risk: "No",
      },
      {
        emp_id: "EMP010",
        name: "Pooja Sahu",
        designation: "QA Engineer",
        reporting_manager: "Sanjay Rao",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Quality Assurance",
        manager: "Sanjay Rao",
        status: "Active",
        wissen_experience: 2.1,
        total_experience: 3.0,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Meets Expectations",
        interview_count: 4,
        rr_percent: 79.8,
        gross_margin: 26.1,
        rb_to_be_paid: 16000,
        month_rb: "Feb",
        pb_to_be_paid: 22000,
        month_pb: "Feb",
        current_annual_base_pay: 560000,
        target_pb_allocated_for_may: 28000,
        allocated_pb_amount: 27000,
        pb_installment: "1",
        new_pb_to_be_offered: 32000,
        new_pb_installment: "2",
        new_rb: 18000,
        hike_amount: 39200,
        hike_pct: 7.0,
        target_pb_next_year: 36000,
        eligible_for_promotion: "No",
        new_title: "QA Engineer",
        at_risk: "No",
      },
      {
        emp_id: "EMP011",
        name: "Deepak Jena",
        designation: "Technical Lead",
        reporting_manager: "Rajesh Sharma",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Rajesh Sharma",
        status: "Active",
        wissen_experience: 5.2,
        total_experience: 7.0,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Outstanding",
        interview_count: 11,
        rr_percent: 97.4,
        gross_margin: 42.2,
        rb_to_be_paid: 35000,
        month_rb: "Mar",
        pb_to_be_paid: 48000,
        month_pb: "Mar",
        current_annual_base_pay: 1200000,
        target_pb_allocated_for_may: 60000,
        allocated_pb_amount: 58000,
        pb_installment: "2",
        new_pb_to_be_offered: 75000,
        new_pb_installment: "2",
        new_rb: 40000,
        hike_amount: 120000,
        hike_pct: 10.0,
        target_pb_next_year: 85000,
        eligible_for_promotion: "Yes",
        new_title: "Engineering Manager",
        at_risk: "No",
      },
      {
        emp_id: "EMP012",
        name: "Swati Pradhan",
        designation: "UI Developer",
        reporting_manager: "Anil Kumar",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Anil Kumar",
        status: "Active",
        wissen_experience: 1.9,
        total_experience: 2.8,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Exceeds Expectations",
        interview_count: 5,
        rr_percent: 87.5,
        gross_margin: 30.5,
        rb_to_be_paid: 18000,
        month_rb: "Mar",
        pb_to_be_paid: 25000,
        month_pb: "Mar",
        current_annual_base_pay: 620000,
        target_pb_allocated_for_may: 31000,
        allocated_pb_amount: 30000,
        pb_installment: "2",
        new_pb_to_be_offered: 38000,
        new_pb_installment: "2",
        new_rb: 21000,
        hike_amount: 49600,
        hike_pct: 8.0,
        target_pb_next_year: 42000,
        eligible_for_promotion: "No",
        new_title: "UI Developer",
        at_risk: "No",
      },
      {
        emp_id: "EMP013",
        name: "Manish Rout",
        designation: "DevOps Engineer",
        reporting_manager: "Rajesh Sharma",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "DevOps",
        manager: "Rajesh Sharma",
        status: "Active",
        wissen_experience: 3.4,
        total_experience: 4.5,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Exceeds Expectations",
        interview_count: 7,
        rr_percent: 90.4,
        gross_margin: 34.5,
        rb_to_be_paid: 24000,
        month_rb: "Mar",
        pb_to_be_paid: 32000,
        month_pb: "Mar",
        current_annual_base_pay: 780000,
        target_pb_allocated_for_may: 39000,
        allocated_pb_amount: 38000,
        pb_installment: "2",
        new_pb_to_be_offered: 48000,
        new_pb_installment: "2",
        new_rb: 26000,
        hike_amount: 70200,
        hike_pct: 9.0,
        target_pb_next_year: 52000,
        eligible_for_promotion: "No",
        new_title: "DevOps Engineer",
        at_risk: "No",
      },
      {
        emp_id: "EMP014",
        name: "Nikita Behera",
        designation: "Business Analyst",
        reporting_manager: "Meera Nair",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Non Technical",
        department: "Business Analysis",
        manager: "Meera Nair",
        status: "Active",
        wissen_experience: 2.8,
        total_experience: 4.0,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Outstanding",
        interview_count: 8,
        rr_percent: 92.7,
        gross_margin: 33.4,
        rb_to_be_paid: 23000,
        month_rb: "Mar",
        pb_to_be_paid: 31000,
        month_pb: "Mar",
        current_annual_base_pay: 750000,
        target_pb_allocated_for_may: 37500,
        allocated_pb_amount: 36000,
        pb_installment: "2",
        new_pb_to_be_offered: 46000,
        new_pb_installment: "2",
        new_rb: 25000,
        hike_amount: 75000,
        hike_pct: 10.0,
        target_pb_next_year: 50000,
        eligible_for_promotion: "Yes",
        new_title: "Senior Business Analyst",
        at_risk: "No",
      },
      {
        emp_id: "EMP015",
        name: "Rakesh Das",
        designation: "Software Developer",
        reporting_manager: "Anil Kumar",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Anil Kumar",
        status: "Active",
        wissen_experience: 1.7,
        total_experience: 2.3,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Meets Expectations",
        interview_count: 3,
        rr_percent: 77.2,
        gross_margin: 25.8,
        rb_to_be_paid: 15000,
        month_rb: "Feb",
        pb_to_be_paid: 21000,
        month_pb: "Feb",
        current_annual_base_pay: 520000,
        target_pb_allocated_for_may: 26000,
        allocated_pb_amount: 25000,
        pb_installment: "1",
        new_pb_to_be_offered: 30000,
        new_pb_installment: "2",
        new_rb: 17000,
        hike_amount: 31200,
        hike_pct: 6.0,
        target_pb_next_year: 34000,
        eligible_for_promotion: "No",
        new_title: "Software Developer",
        at_risk: "Yes",
      },
      {
        emp_id: "EMP016",
        name: "Kavya Panda",
        designation: "QA Analyst",
        reporting_manager: "Sanjay Rao",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Quality Assurance",
        manager: "Sanjay Rao",
        status: "Active",
        wissen_experience: 2.5,
        total_experience: 3.7,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Exceeds Expectations",
        interview_count: 6,
        rr_percent: 85.9,
        gross_margin: 29.1,
        rb_to_be_paid: 19000,
        month_rb: "Mar",
        pb_to_be_paid: 27000,
        month_pb: "Mar",
        current_annual_base_pay: 600000,
        target_pb_allocated_for_may: 30000,
        allocated_pb_amount: 29000,
        pb_installment: "2",
        new_pb_to_be_offered: 36000,
        new_pb_installment: "2",
        new_rb: 20000,
        hike_amount: 48000,
        hike_pct: 8.0,
        target_pb_next_year: 40000,
        eligible_for_promotion: "No",
        new_title: "QA Analyst",
        at_risk: "No",
      },
      {
        emp_id: "EMP017",
        name: "Arjun Mishra",
        designation: "Software Engineer",
        reporting_manager: "Rajesh Sharma",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Rajesh Sharma",
        status: "Active",
        wissen_experience: 2.9,
        total_experience: 4.1,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Exceeds Expectations",
        interview_count: 7,
        rr_percent: 89.8,
        gross_margin: 33.1,
        rb_to_be_paid: 22000,
        month_rb: "Mar",
        pb_to_be_paid: 30000,
        month_pb: "Mar",
        current_annual_base_pay: 700000,
        target_pb_allocated_for_may: 35000,
        allocated_pb_amount: 34000,
        pb_installment: "2",
        new_pb_to_be_offered: 43000,
        new_pb_installment: "2",
        new_rb: 24000,
        hike_amount: 63000,
        hike_pct: 9.0,
        target_pb_next_year: 48000,
        eligible_for_promotion: "No",
        new_title: "Software Engineer",
        at_risk: "No",
      },
      {
        emp_id: "EMP018",
        name: "Isha Mohanty",
        designation: "HR Executive",
        reporting_manager: "Meera Nair",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Non Technical",
        department: "Human Resources",
        manager: "Meera Nair",
        status: "Active",
        wissen_experience: 1.6,
        total_experience: 2.4,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Meets Expectations",
        interview_count: 4,
        rr_percent: 76.8,
        gross_margin: 24.9,
        rb_to_be_paid: 14000,
        month_rb: "Feb",
        pb_to_be_paid: 20000,
        month_pb: "Feb",
        current_annual_base_pay: 520000,
        target_pb_allocated_for_may: 26000,
        allocated_pb_amount: 25000,
        pb_installment: "1",
        new_pb_to_be_offered: 30000,
        new_pb_installment: "2",
        new_rb: 16000,
        hike_amount: 31200,
        hike_pct: 6.0,
        target_pb_next_year: 34000,
        eligible_for_promotion: "No",
        new_title: "HR Executive",
        at_risk: "Yes",
      },
      {
        emp_id: "EMP019",
        name: "Siddharth Das",
        designation: "Senior Developer",
        reporting_manager: "Anil Kumar",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Anil Kumar",
        status: "Active",
        wissen_experience: 4.0,
        total_experience: 5.5,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Outstanding",
        interview_count: 10,
        rr_percent: 95.6,
        gross_margin: 39.4,
        rb_to_be_paid: 30000,
        month_rb: "Mar",
        pb_to_be_paid: 42000,
        month_pb: "Mar",
        current_annual_base_pay: 960000,
        target_pb_allocated_for_may: 48000,
        allocated_pb_amount: 47000,
        pb_installment: "2",
        new_pb_to_be_offered: 60000,
        new_pb_installment: "2",
        new_rb: 32000,
        hike_amount: 96000,
        hike_pct: 10.0,
        target_pb_next_year: 68000,
        eligible_for_promotion: "Yes",
        new_title: "Technical Lead",
        at_risk: "No",
      },
      {
        emp_id: "EMP020",
        name: "Monalisa Rout",
        designation: "UI Developer",
        reporting_manager: "Anil Kumar",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Anil Kumar",
        status: "Active",
        wissen_experience: 2.3,
        total_experience: 3.3,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Exceeds Expectations",
        interview_count: 5,
        rr_percent: 86.3,
        gross_margin: 30.8,
        rb_to_be_paid: 18000,
        month_rb: "Mar",
        pb_to_be_paid: 25000,
        month_pb: "Mar",
        current_annual_base_pay: 640000,
        target_pb_allocated_for_may: 32000,
        allocated_pb_amount: 31000,
        pb_installment: "2",
        new_pb_to_be_offered: 39000,
        new_pb_installment: "2",
        new_rb: 22000,
        hike_amount: 51200,
        hike_pct: 8.0,
        target_pb_next_year: 43000,
        eligible_for_promotion: "No",
        new_title: "UI Developer",
        at_risk: "No",
      },
      {
        emp_id: "EMP021",
        name: "Suman Behera",
        designation: "Software Engineer",
        reporting_manager: "Rajesh Sharma",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Rajesh Sharma",
        status: "Active",
        wissen_experience: 3.2,
        total_experience: 4.6,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Exceeds Expectations",
        interview_count: 8,
        rr_percent: 90.1,
        gross_margin: 34.0,
        rb_to_be_paid: 23000,
        month_rb: "Mar",
        pb_to_be_paid: 32000,
        month_pb: "Mar",
        current_annual_base_pay: 760000,
        target_pb_allocated_for_may: 38000,
        allocated_pb_amount: 37000,
        pb_installment: "2",
        new_pb_to_be_offered: 47000,
        new_pb_installment: "2",
        new_rb: 26000,
        hike_amount: 68400,
        hike_pct: 9.0,
        target_pb_next_year: 52000,
        eligible_for_promotion: "No",
        new_title: "Software Engineer",
        at_risk: "No",
      },
      {
        emp_id: "EMP022",
        name: "Tanvi Singh",
        designation: "Business Analyst",
        reporting_manager: "Meera Nair",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Non Technical",
        department: "Business Analysis",
        manager: "Meera Nair",
        status: "Active",
        wissen_experience: 3.1,
        total_experience: 4.4,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Outstanding",
        interview_count: 9,
        rr_percent: 93.6,
        gross_margin: 35.2,
        rb_to_be_paid: 25000,
        month_rb: "Mar",
        pb_to_be_paid: 34000,
        month_pb: "Mar",
        current_annual_base_pay: 800000,
        target_pb_allocated_for_may: 40000,
        allocated_pb_amount: 39000,
        pb_installment: "2",
        new_pb_to_be_offered: 50000,
        new_pb_installment: "2",
        new_rb: 28000,
        hike_amount: 80000,
        hike_pct: 10.0,
        target_pb_next_year: 56000,
        eligible_for_promotion: "Yes",
        new_title: "Senior Business Analyst",
        at_risk: "No",
      },
      {
        emp_id: "EMP023",
        name: "Harish Kumar",
        designation: "DevOps Engineer",
        reporting_manager: "Rajesh Sharma",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "DevOps",
        manager: "Rajesh Sharma",
        status: "Active",
        wissen_experience: 2.6,
        total_experience: 3.8,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Meets Expectations",
        interview_count: 4,
        rr_percent: 80.5,
        gross_margin: 27.2,
        rb_to_be_paid: 17000,
        month_rb: "Feb",
        pb_to_be_paid: 23000,
        month_pb: "Feb",
        current_annual_base_pay: 650000,
        target_pb_allocated_for_may: 32500,
        allocated_pb_amount: 31000,
        pb_installment: "1",
        new_pb_to_be_offered: 38000,
        new_pb_installment: "2",
        new_rb: 21000,
        hike_amount: 39000,
        hike_pct: 6.0,
        target_pb_next_year: 42000,
        eligible_for_promotion: "No",
        new_title: "DevOps Engineer",
        at_risk: "Yes",
      },
      {
        emp_id: "EMP024",
        name: "Jyoti Sahu",
        designation: "QA Engineer",
        reporting_manager: "Sanjay Rao",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Quality Assurance",
        manager: "Sanjay Rao",
        status: "Active",
        wissen_experience: 3.0,
        total_experience: 4.2,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Exceeds Expectations",
        interview_count: 6,
        rr_percent: 88.7,
        gross_margin: 31.0,
        rb_to_be_paid: 20000,
        month_rb: "Mar",
        pb_to_be_paid: 28000,
        month_pb: "Mar",
        current_annual_base_pay: 680000,
        target_pb_allocated_for_may: 34000,
        allocated_pb_amount: 33000,
        pb_installment: "2",
        new_pb_to_be_offered: 42000,
        new_pb_installment: "2",
        new_rb: 23000,
        hike_amount: 54400,
        hike_pct: 8.0,
        target_pb_next_year: 46000,
        eligible_for_promotion: "No",
        new_title: "QA Engineer",
        at_risk: "No",
      },
      {
        emp_id: "EMP025",
        name: "Ashish Pradhan",
        designation: "Software Developer",
        reporting_manager: "Anil Kumar",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Anil Kumar",
        status: "Active",
        wissen_experience: 4.3,
        total_experience: 6.0,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Outstanding",
        interview_count: 12,
        rr_percent: 96.8,
        gross_margin: 41.0,
        rb_to_be_paid: 32000,
        month_rb: "Mar",
        pb_to_be_paid: 45000,
        month_pb: "Mar",
        current_annual_base_pay: 1000000,
        target_pb_allocated_for_may: 50000,
        allocated_pb_amount: 49000,
        pb_installment: "2",
        new_pb_to_be_offered: 65000,
        new_pb_installment: "2",
        new_rb: 35000,
        hike_amount: 100000,
        hike_pct: 10.0,
        target_pb_next_year: 72000,
        eligible_for_promotion: "Yes",
        new_title: "Senior Software Developer",
        at_risk: "No",
      },
      {
        emp_id: "EMP026",
        name: "Neha Das",
        designation: "HR Executive",
        reporting_manager: "Meera Nair",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Non Technical",
        department: "Human Resources",
        manager: "Meera Nair",
        status: "Active",
        wissen_experience: 2.7,
        total_experience: 3.9,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Exceeds Expectations",
        interview_count: 7,
        rr_percent: 87.9,
        gross_margin: 28.8,
        rb_to_be_paid: 19000,
        month_rb: "Mar",
        pb_to_be_paid: 26000,
        month_pb: "Mar",
        current_annual_base_pay: 600000,
        target_pb_allocated_for_may: 30000,
        allocated_pb_amount: 29000,
        pb_installment: "2",
        new_pb_to_be_offered: 37000,
        new_pb_installment: "2",
        new_rb: 21000,
        hike_amount: 48000,
        hike_pct: 8.0,
        target_pb_next_year: 41000,
        eligible_for_promotion: "No",
        new_title: "HR Executive",
        at_risk: "No",
      },
      {
        emp_id: "EMP027",
        name: "Rajesh Nayak",
        designation: "Technical Lead",
        reporting_manager: "Rajesh Sharma",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Rajesh Sharma",
        status: "Active",
        wissen_experience: 5.0,
        total_experience: 6.8,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Outstanding",
        interview_count: 10,
        rr_percent: 98.1,
        gross_margin: 43.0,
        rb_to_be_paid: 34000,
        month_rb: "Mar",
        pb_to_be_paid: 47000,
        month_pb: "Mar",
        current_annual_base_pay: 1100000,
        target_pb_allocated_for_may: 55000,
        allocated_pb_amount: 54000,
        pb_installment: "2",
        new_pb_to_be_offered: 70000,
        new_pb_installment: "2",
        new_rb: 38000,
        hike_amount: 121000,
        hike_pct: 11.0,
        target_pb_next_year: 80000,
        eligible_for_promotion: "Yes",
        new_title: "Engineering Manager",
        at_risk: "No",
      },
      {
        emp_id: "EMP028",
        name: "Lopamudra Das",
        designation: "Business Analyst",
        reporting_manager: "Meera Nair",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Non Technical",
        department: "Business Analysis",
        manager: "Meera Nair",
        status: "Active",
        wissen_experience: 1.4,
        total_experience: 2.1,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Needs Improvement",
        interview_count: 2,
        rr_percent: 68.5,
        gross_margin: 21.5,
        rb_to_be_paid: 12000,
        month_rb: "Feb",
        pb_to_be_paid: 16000,
        month_pb: "Feb",
        current_annual_base_pay: 480000,
        target_pb_allocated_for_may: 24000,
        allocated_pb_amount: 22000,
        pb_installment: "1",
        new_pb_to_be_offered: 26000,
        new_pb_installment: "2",
        new_rb: 14000,
        hike_amount: 19200,
        hike_pct: 4.0,
        target_pb_next_year: 28000,
        eligible_for_promotion: "No",
        new_title: "Business Analyst",
        at_risk: "Yes",
      },
      {
        emp_id: "EMP029",
        name: "Gaurav Mohanty",
        designation: "Software Engineer",
        reporting_manager: "Anil Kumar",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Engineering",
        manager: "Anil Kumar",
        status: "Active",
        wissen_experience: 2.0,
        total_experience: 3.0,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Meets Expectations",
        interview_count: 4,
        rr_percent: 79.4,
        gross_margin: 26.5,
        rb_to_be_paid: 16000,
        month_rb: "Feb",
        pb_to_be_paid: 22000,
        month_pb: "Feb",
        current_annual_base_pay: 580000,
        target_pb_allocated_for_may: 29000,
        allocated_pb_amount: 28000,
        pb_installment: "1",
        new_pb_to_be_offered: 34000,
        new_pb_installment: "2",
        new_rb: 19000,
        hike_amount: 40600,
        hike_pct: 7.0,
        target_pb_next_year: 38000,
        eligible_for_promotion: "No",
        new_title: "Software Engineer",
        at_risk: "No",
      },
      {
        emp_id: "EMP030",
        name: "Sanjana Patnaik",
        designation: "Senior QA Engineer",
        reporting_manager: "Sanjay Rao",
        comp_manager: "Neha Singh",
        appraiser_tech_ed: "Technical",
        department: "Quality Assurance",
        manager: "Sanjay Rao",
        status: "Active",
        wissen_experience: 4.1,
        total_experience: 5.7,
        last_appraisal_date: "2026-03-31",
        manager_rating: "Outstanding",
        interview_count: 10,
        rr_percent: 94.8,
        gross_margin: 37.6,
        rb_to_be_paid: 27000,
        month_rb: "Mar",
        pb_to_be_paid: 37000,
        month_pb: "Mar",
        current_annual_base_pay: 880000,
        target_pb_allocated_for_may: 44000,
        allocated_pb_amount: 43000,
        pb_installment: "2",
        new_pb_to_be_offered: 55000,
        new_pb_installment: "2",
        new_rb: 30000,
        hike_amount: 88000,
        hike_pct: 10.0,
        target_pb_next_year: 62000,
        eligible_for_promotion: "Yes",
        new_title: "QA Lead",
        at_risk: "No",
      },
    ];

    const result = await table.insertRows(employees);

    context.log(`Successfully inserted ${result.length} employees`);

    basicIO.write(
      JSON.stringify({
        success: true,
        insertedCount: result.length,
        message: `${result.length} employees inserted successfully`,
      }),
    );
  } catch (error) {
    context.log("Error inserting employees: " + error.message);

    basicIO.write(
      JSON.stringify({
        success: false,
        message: error.message,
      }),
    );
  }

  context.close();
};
