import { useEffect, useMemo, useRef, useState } from "react";
import { payrollCycleRequest } from "@/lib/payroll-cycle-api";

const COLS = [
  { key: "empId", label: "Employee ID", type: "text", frozen: true },
  { key: "cycle", label: "Cycle", type: "text" },
  { key: "batch", label: "Source Batch", type: "text" },
  { key: "empName", label: "Employee Name", type: "text", cat: "master" },
  { key: "designation", label: "Designation", type: "text", cat: "master" },
  { key: "compManager", label: "Compensation Manager", type: "text", cat: "master" },
  { key: "superManager", label: "Super Manager", type: "text", cat: "master" },
  { key: "managerMail", label: "Manager Email", type: "text", cat: "master" },
  {
    key: "basePay",
    label: "Base Pay",
    type: "number",
    cat: "master",
    money: true,
  },
  {
    key: "basePay_yoy",
    label: "YoY %",
    type: "number",
    cat: "calc",
    isYoy: true,
    baseKey: "basePay",
  },
  {
    key: "targetPB",
    label: "Target PB",
    type: "number",
    cat: "master",
    money: true,
  },
  {
    key: "allocPB",
    label: "Allocated PB",
    type: "number",
    cat: "input",
    money: true,
  },
  {
    key: "newPB",
    label: "New PB",
    type: "number",
    cat: "input",
    money: true,
  },
  { key: "newRB", label: "New Retention Bonus", type: "number", cat: "input", money: true },
  {
    key: "hikeAmt",
    label: "Hike Amount",
    type: "number",
    cat: "input",
    money: true,
  },
  { key: "promo", label: "Promotion", type: "text", cat: "input" },
  { key: "newTitle", label: "New Title", type: "text", cat: "input" },
  {
    key: "totalPB",
    label: "Total PB",
    type: "number",
    cat: "calc",
    money: true,
    computed: true,
  },
  {
    key: "totalBonus",
    label: "Total Bonus",
    type: "number",
    cat: "calc",
    money: true,
    computed: true,
  },
  {
    key: "totalBonus_yoy",
    label: "YoY %",
    type: "number",
    cat: "calc",
    isYoy: true,
    baseKey: "totalBonus",
  },
  {
    key: "hikePct",
    label: "Hike %",
    type: "number",
    cat: "calc",
    pct: true,
    computed: true,
  },
  {
    key: "newBasePay",
    label: "New Base Pay",
    type: "number",
    cat: "calc",
    money: true,
    computed: true,
  },
  {
    key: "totalCtc",
    label: "Total CTC",
    type: "number",
    cat: "calc",
    money: true,
    computed: true,
  },
  {
    key: "totalCtc_yoy",
    label: "YoY %",
    type: "number",
    cat: "calc",
    isYoy: true,
    baseKey: "totalCtc",
  },
];